---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: fahclient-centos8
  namespace: fahclient
spec:
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - fahclient-centos8
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
