apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: fah-placement
  namespace: fahclient
  labels:
    app: fahclient-centos8
spec:
  clusterSelector:
    matchLabels: 
      cloud: Azure
