---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: etherpad-app
  namespace: etherpad
spec:
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - etherpad-app
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
