apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: etherpad-pr
  namespace: etherpad
  labels:
    app: etherpad-app 
spec:
  clusterReplicas: 2
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchLabels:
      environment: dev
      #vendor: OpenShift
