apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: etherpad-app
  namespace: etherpad
  labels:
    app: etherpad-app
  annotations:
    apps.open-cluster-management.io/git-path: app-lifecycle/etherpad
    apps.open-cluster-management.io/git-branch: master
spec:
  channel: etherpad/etherpad-app-latest
  hooksecretref:
    name: toweraccess
  placement:
    placementRef:
      kind: PlacementRule
      name: etherpad-pr
