---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-policies-github
  namespace: open-cluster-management
data:
    path: governance/policies/CM-Configuration-Management
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: demo-policies
  namespace: open-cluster-management
spec:
  channel: open-cluster-management/demo-policies
  placement:
    local: true
  packageFilter:
    filterRef:
      name: demo-policies-github

